training:
  experiment_name: 最好U网-310真:256假-早停-lr0.0005-不用调度-第1
  checkpoint_dir: "checkpoints/"
  log_neptune: true
  batch_size: 32
  num_epochs: 200
  steps_per_epoch:
  use_evaluation_metric: true
  save_best: true
  use_scheduler: false
  scheduler_type: # "exponential", "warmup_cosine", "OneCycleLR", "ReduceLROnPlateau"
  learning_rate: 0.0005
  scheduler_gamma: 0.8
  pct_start: 0.5
  min_lr: 0.0001
  min_delta: 0.0             # -1 -> no early stopping
  patience: 10
  weight_decay: 0.0001
  tensorboard: false
  seed: 42