training:
  experiment_name: real_data-best_unet-use_scheduler-delta_0.01_100-epoch # e.g. "real_data-best_unet-use_scheduler-delta_-0.01"
  checkpoint_dir: "checkpoints/"
  log_neptune: true
  batch_size: 32
  num_epochs: 10
  steps_per_epoch:
  use_evaluation_metric: true
  save_best: true
  use_scheduler: true
  scheduler_gamma: 0.9
  early_stopping: true
  min_delta: 0.001  # set to e.g. -99999 to not use early stopping
  patience: 10
  learning_rate: 0.01
  weight_decay: 0.0001
  tensorboard: false
  seed: 42