training:
  experiment_name: test-preprocessing #最好U网-0真:256假均匀高斯-不早停-lr0.001-用cyc调度0.3-第1
  checkpoint_dir: "checkpoints/"
  log_neptune: true
  batch_size: 32
  num_epochs: 200
  use_evaluation_metric: true
  save_best: true
  use_scheduler: true
  scheduler_type: OneCycleLR # "exponential", "warmup_cosine", "OneCycleLR", "ReduceLROnPlateau"
  learning_rate: 0.001
  scheduler_gamma: 0.8
  pct_start: 0.3
  min_lr: 1.0e-05
  min_delta: -1.0             # -1 -> no early stopping
  patience: 20
  weight_decay: 0.0001
  seed: 42
  synth_ratio: 1